#define COMBO(NAME, KEYS, BINDING, LAYERS) \
    ZMK_COMBO(NAME, BINDING, KEYS, LAYERS, COMBO_TERM, COMBO_IDLE_SLOW)

#define COMBO_FAST(NAME, KEYS, BINDING, LAYERS) \
    ZMK_COMBO(NAME, BINDING, KEYS, LAYERS, COMBO_TERM_FAST, COMBO_IDLE_SLOW)

#define COMBO_SLOW(NAME, KEYS, BINDING, LAYERS) \
    ZMK_COMBO(NAME, BINDING, KEYS, LAYERS, COMBO_TERM_SLOW, COMBO_IDLE_FAST)
